[package]
name = "bits33vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bits33core = { path = "../bits33core" }
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1.2"